[package]
name = "supervisor"
version = "0.1.0"
authors = ["ArthurYu <yuya008@aliyun.com>"]
edition = "2018"


[dependencies]
log = "0.4"
quick-error = "2.0"
rand = "0.7"
uuid = { version = "0.8", features = ["serde", "v4"] }
crossbeam = "0.7"
rayon = "1.4"