[package]
name = "supervisor"
version = "0.1.0"
authors = ["yuya <ya.yu@target-energysolutions.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
quick-error = "2.0"
